/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*GameThriveInitialize_t)(const char* appId, const char* googleProjectNumber, GameThriveNotificationReceivedCallbackFn callbackFn, s3eBool autoRegister);
typedef       void(*GameThriveSendTag_t)(const char* key, const char* value);
typedef       void(*GameThriveGetTags_t)(GameThriveTagsReceivedCallbackFn callbackFn);
typedef       void(*GameThriveDeleteTag_t)(const char* key);
typedef       void(*GameThriveSendPurchase_t)(const double* amount);
typedef       void(*GameThriveGetIdsAvailable_t)(GameThriveIdsAvailableCallbackFn callbackFn);
typedef        int(*GameThriveSystemPaused_t)(void* systemData, void* userData);
typedef        int(*GameThriveSystemResume_t)(void* systemData, void* userData);
typedef       void(*GameThriveRegisterForPushNotifications_t)();
typedef       void(*GameThriveEnableVibrate_t)(s3eBool enable);
typedef       void(*GameThriveEnableSound_t)(s3eBool enable);
typedef       void(*OneSignalInitialize_t)(const char* appId, const char* googleProjectNumber, OneSignalNotificationReceivedCallbackFn callbackFn, s3eBool autoRegister);
typedef       void(*OneSignalSendTag_t)(const char* key, const char* value);
typedef       void(*OneSignalGetTags_t)(OneSignalTagsReceivedCallbackFn callbackFn);
typedef       void(*OneSignalDeleteTag_t)(const char* key);
typedef       void(*OneSignalSendPurchase_t)(const double* amount);
typedef       void(*OneSignalGetIdsAvailable_t)(OneSignalIdsAvailableCallbackFn callbackFn);
typedef        int(*OneSignalSystemPaused_t)(void* systemData, void* userData);
typedef        int(*OneSignalSystemResume_t)(void* systemData, void* userData);
typedef       void(*OneSignalRegisterForPushNotifications_t)();
typedef       void(*OneSignalEnableVibrate_t)(s3eBool enable);
typedef       void(*OneSignalEnableSound_t)(s3eBool enable);
typedef       void(*OneSignalEnableInAppAlertNotification_t)(s3eBool enable);
typedef       void(*OneSignalEnableNotificationsWhenActive_t)(s3eBool enable);
typedef       void(*OneSignalSetSubscription_t)(s3eBool enable);
typedef       void(*OneSignalPostNotification_t)(const char* jsonData);

/**
 * struct that gets filled in by s3eOneSignalRegister
 */
typedef struct s3eOneSignalFuncs
{
    GameThriveInitialize_t m_GameThriveInitialize;
    GameThriveSendTag_t m_GameThriveSendTag;
    GameThriveGetTags_t m_GameThriveGetTags;
    GameThriveDeleteTag_t m_GameThriveDeleteTag;
    GameThriveSendPurchase_t m_GameThriveSendPurchase;
    GameThriveGetIdsAvailable_t m_GameThriveGetIdsAvailable;
    GameThriveSystemPaused_t m_GameThriveSystemPaused;
    GameThriveSystemResume_t m_GameThriveSystemResume;
    GameThriveRegisterForPushNotifications_t m_GameThriveRegisterForPushNotifications;
    GameThriveEnableVibrate_t m_GameThriveEnableVibrate;
    GameThriveEnableSound_t m_GameThriveEnableSound;
    OneSignalInitialize_t m_OneSignalInitialize;
    OneSignalSendTag_t m_OneSignalSendTag;
    OneSignalGetTags_t m_OneSignalGetTags;
    OneSignalDeleteTag_t m_OneSignalDeleteTag;
    OneSignalSendPurchase_t m_OneSignalSendPurchase;
    OneSignalGetIdsAvailable_t m_OneSignalGetIdsAvailable;
    OneSignalSystemPaused_t m_OneSignalSystemPaused;
    OneSignalSystemResume_t m_OneSignalSystemResume;
    OneSignalRegisterForPushNotifications_t m_OneSignalRegisterForPushNotifications;
    OneSignalEnableVibrate_t m_OneSignalEnableVibrate;
    OneSignalEnableSound_t m_OneSignalEnableSound;
    OneSignalEnableInAppAlertNotification_t m_OneSignalEnableInAppAlertNotification;
    OneSignalEnableNotificationsWhenActive_t m_OneSignalEnableNotificationsWhenActive;
    OneSignalSetSubscription_t m_OneSignalSetSubscription;
    OneSignalPostNotification_t m_OneSignalPostNotification;
} s3eOneSignalFuncs;
