/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eOneSignal.h"


// Define S3E_EXT_SKIP_LOADER_CALL_LOCK on the user-side to skip LoaderCallStart/LoaderCallDone()-entry.
// e.g. in s3eNUI this is used for generic user-side IwUI-based implementation.
#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
#if defined I3D_ARCH_MIPS || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)) || defined I3D_ARCH_NACLX86_64
// For platforms missing stack-switching (MIPS, WP8, NaCl, etc.) make loader-entry via LoaderCallStart/LoaderCallDone() on the user-side.
#define LOADER_CALL_LOCK
#endif
#endif


#include "s3eOneSignal_interface.h"

static s3eOneSignalFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xf8792e70, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eOneSignal");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xf8792e70, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eOneSignalAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

void GameThriveInitialize(const char* appId, const char* googleProjectNumber, GameThriveNotificationReceivedCallbackFn callbackFn, s3eBool autoRegister)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[0] func: GameThriveInitialize"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveInitialize);
#endif

    g_Ext.m_GameThriveInitialize(appId, googleProjectNumber, callbackFn, autoRegister);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveInitialize);
#endif

    return;
}

void GameThriveSendTag(const char* key, const char* value)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[1] func: GameThriveSendTag"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveSendTag);
#endif

    g_Ext.m_GameThriveSendTag(key, value);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveSendTag);
#endif

    return;
}

void GameThriveGetTags(GameThriveTagsReceivedCallbackFn callbackFn)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[2] func: GameThriveGetTags"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveGetTags);
#endif

    g_Ext.m_GameThriveGetTags(callbackFn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveGetTags);
#endif

    return;
}

void GameThriveDeleteTag(const char* key)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[3] func: GameThriveDeleteTag"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveDeleteTag);
#endif

    g_Ext.m_GameThriveDeleteTag(key);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveDeleteTag);
#endif

    return;
}

void GameThriveSendPurchase(const double* amount)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[4] func: GameThriveSendPurchase"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveSendPurchase);
#endif

    g_Ext.m_GameThriveSendPurchase(amount);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveSendPurchase);
#endif

    return;
}

void GameThriveGetIdsAvailable(GameThriveIdsAvailableCallbackFn callbackFn)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[5] func: GameThriveGetIdsAvailable"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveGetIdsAvailable);
#endif

    g_Ext.m_GameThriveGetIdsAvailable(callbackFn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveGetIdsAvailable);
#endif

    return;
}

int GameThriveSystemPaused(void* systemData, void* userData)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[6] func: GameThriveSystemPaused"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveSystemPaused);
#endif

    int ret = g_Ext.m_GameThriveSystemPaused(systemData, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveSystemPaused);
#endif

    return ret;
}

int GameThriveSystemResume(void* systemData, void* userData)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[7] func: GameThriveSystemResume"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveSystemResume);
#endif

    int ret = g_Ext.m_GameThriveSystemResume(systemData, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveSystemResume);
#endif

    return ret;
}

void GameThriveRegisterForPushNotifications()
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[8] func: GameThriveRegisterForPushNotifications"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveRegisterForPushNotifications);
#endif

    g_Ext.m_GameThriveRegisterForPushNotifications();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveRegisterForPushNotifications);
#endif

    return;
}

void GameThriveEnableVibrate(s3eBool enable)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[9] func: GameThriveEnableVibrate"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveEnableVibrate);
#endif

    g_Ext.m_GameThriveEnableVibrate(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveEnableVibrate);
#endif

    return;
}

void GameThriveEnableSound(s3eBool enable)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[10] func: GameThriveEnableSound"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_GameThriveEnableSound);
#endif

    g_Ext.m_GameThriveEnableSound(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_GameThriveEnableSound);
#endif

    return;
}

void OneSignalInitialize(const char* appId, const char* googleProjectNumber, OneSignalNotificationReceivedCallbackFn callbackFn, s3eBool autoRegister)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[11] func: OneSignalInitialize"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalInitialize);
#endif

    g_Ext.m_OneSignalInitialize(appId, googleProjectNumber, callbackFn, autoRegister);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalInitialize);
#endif

    return;
}

void OneSignalSendTag(const char* key, const char* value)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[12] func: OneSignalSendTag"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalSendTag);
#endif

    g_Ext.m_OneSignalSendTag(key, value);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalSendTag);
#endif

    return;
}

void OneSignalGetTags(OneSignalTagsReceivedCallbackFn callbackFn)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[13] func: OneSignalGetTags"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalGetTags);
#endif

    g_Ext.m_OneSignalGetTags(callbackFn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalGetTags);
#endif

    return;
}

void OneSignalDeleteTag(const char* key)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[14] func: OneSignalDeleteTag"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalDeleteTag);
#endif

    g_Ext.m_OneSignalDeleteTag(key);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalDeleteTag);
#endif

    return;
}

void OneSignalSendPurchase(const double* amount)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[15] func: OneSignalSendPurchase"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalSendPurchase);
#endif

    g_Ext.m_OneSignalSendPurchase(amount);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalSendPurchase);
#endif

    return;
}

void OneSignalGetIdsAvailable(OneSignalIdsAvailableCallbackFn callbackFn)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[16] func: OneSignalGetIdsAvailable"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalGetIdsAvailable);
#endif

    g_Ext.m_OneSignalGetIdsAvailable(callbackFn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalGetIdsAvailable);
#endif

    return;
}

int OneSignalSystemPaused(void* systemData, void* userData)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[17] func: OneSignalSystemPaused"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalSystemPaused);
#endif

    int ret = g_Ext.m_OneSignalSystemPaused(systemData, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalSystemPaused);
#endif

    return ret;
}

int OneSignalSystemResume(void* systemData, void* userData)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[18] func: OneSignalSystemResume"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalSystemResume);
#endif

    int ret = g_Ext.m_OneSignalSystemResume(systemData, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalSystemResume);
#endif

    return ret;
}

void OneSignalRegisterForPushNotifications()
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[19] func: OneSignalRegisterForPushNotifications"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalRegisterForPushNotifications);
#endif

    g_Ext.m_OneSignalRegisterForPushNotifications();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalRegisterForPushNotifications);
#endif

    return;
}

void OneSignalEnableVibrate(s3eBool enable)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[20] func: OneSignalEnableVibrate"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalEnableVibrate);
#endif

    g_Ext.m_OneSignalEnableVibrate(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalEnableVibrate);
#endif

    return;
}

void OneSignalEnableSound(s3eBool enable)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[21] func: OneSignalEnableSound"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalEnableSound);
#endif

    g_Ext.m_OneSignalEnableSound(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalEnableSound);
#endif

    return;
}

void OneSignalEnableInAppAlertNotification(s3eBool enable)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[22] func: OneSignalEnableInAppAlertNotification"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalEnableInAppAlertNotification);
#endif

    g_Ext.m_OneSignalEnableInAppAlertNotification(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalEnableInAppAlertNotification);
#endif

    return;
}

void OneSignalEnableNotificationsWhenActive(s3eBool enable)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[23] func: OneSignalEnableNotificationsWhenActive"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalEnableNotificationsWhenActive);
#endif

    g_Ext.m_OneSignalEnableNotificationsWhenActive(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalEnableNotificationsWhenActive);
#endif

    return;
}

void OneSignalSetSubscription(s3eBool enable)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[24] func: OneSignalSetSubscription"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalSetSubscription);
#endif

    g_Ext.m_OneSignalSetSubscription(enable);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalSetSubscription);
#endif

    return;
}

void OneSignalPostNotification(const char* jsonData)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[25] func: OneSignalPostNotification"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalPostNotification);
#endif

    g_Ext.m_OneSignalPostNotification(jsonData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalPostNotification);
#endif

    return;
}

void OneSignalPostNotificationWithCallback(const char* jsonData, OneSignalPostNotificationCallbackFn callbackSuccessFn, OneSignalPostNotificationCallbackFn callbackFailureFn)
{
    IwTrace(ONESIGNAL_VERBOSE, ("calling s3eOneSignal[26] func: OneSignalPostNotificationWithCallback"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_OneSignalPostNotificationWithCallback);
#endif

    g_Ext.m_OneSignalPostNotificationWithCallback(jsonData, callbackSuccessFn, callbackFailureFn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_OneSignalPostNotificationWithCallback);
#endif

    return;
}
