/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EONESIGNAL_AUTODEFS_H
#define S3EONESIGNAL_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ONESIGNAL_NAME "s3eOneSignal"
#define S3E_EXT_ONESIGNAL_HASH 0xf8792e70

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eOneSignal", 27)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EONESIGNAL_AUTODEFS_H */
